### ISSUE TITLE
Use display: block for konvajs-content

### ISSUE THREAD

**Issue by pronebird** [konvajs/konva#42]
This bug (or feature) has been around for a while and I always had to solve it manually with very aggressive CSS. Before it was `.kineticjs-content`. Without this fix I get scrollbars all over the place on fullscreen canvas. Can we remove inline-block from canvas element once and forever for the love of god?

```css
.konvajs-content { display: block !important; }
```
